apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-standalone
spec:
  selector:
    matchLabels:
      app: wiremock-standalone
  replicas: 2
  template:
    metadata:
      labels:
        app: wiremock-standalone
    spec:
      containers:
      - name: wiremock-standalone
        image: peeweeto/wiremock-standalone:2.0
        ports:
        - containerPort: 8080
